### ISSUE TITLE
Reverse the order of the package version list

### ISSUE THREAD

**Issue by Xavion** [pbrisbin/downgrade#57]
Please reverse the order of the list. In other words, the most recent editions of packages should be shown at the bottom of the screen. It makes sense that people looking for earlier versions should have to scroll back further!

See my comments from the June of 2017 on the ['downgrade' AUR webpage](https://aur.archlinux.org/packages/downgrade/) for more information.

**Comment by pbrisbin** [comment]
I believe this is effectively closed by 92a135f704ca79ce9f0dd90d19cfc6f575f5597d.

Results are presented 30-at-a-time now. This should solve the problem of recent packages flying through scroll-back, and allow us to retain most-recent-first overall sorting.

**Comment by friday** [comment]
30 at a time is nice, but the issue still remains imo. The terminal window may be less than 31 lines high, and in addition the bottom is where the users focus is. [yay](https://github.com/Jguer/yay/) for example shows the most relevant results at the bottom and so does [fzf](https://github.com/junegunn/fzf).

**Comment by pbrisbin** [comment]
Hmm, I think to have most recent pages first, but within each page have items sorted most recent last is a bit strange. If the issue is still about important items scrolling off, I wonder if there's a better fix:

Can you set a smaller `DOWNGRADE_PAGE_SIZE` that works well enough for how big your terminals usually are?

What if the page size we're dynamic based on current terminal height? That would probably be a pretty simple feature to add, and let's us keep a consistent overall sort.

**Comment by pbrisbin** [comment]
I don't remember who decided pagination was a better fix than just reversing the list, but I thought *someone* wanted it. If the solution here is to rip that out and just reverse a simple list, I wouldn't be against it.

**Comment by friday** [comment]
I've come to expect the bottom result to be the most relevant, through the use of other modern cli utilities, and think it makes sense since it's less effortful. I can't say it's a standard or even an emerging standard though. It could be a bit strange or unorthodox if you're used to the opposite I guess.

I certainly can live with it either way since I don't downgrade that often. Just wanted to share my perspective.

Thanks for listening! :+1:

**Comment by pbrisbin** [comment]
I pulled out the pagination and reversed the out, as of v6.1.0.
